In [3]:
import numpy as np

In [4]:
arr = [1,2,3,4,5,6] # 1d


In [5]:
np_array = np.array(arr)

In [8]:
print(arr)
print(type(arr))
print(np_array)
print(type(np_array))

[1, 2, 3, 4, 5, 6]
<class 'list'>
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [9]:
scores     = np.array([88, 92, 74, 95, 61])
prices     = np.array([29.99, 14.50, 99.00, 4.75]) # float takes half memory as compared to int values
print(scores)
print(prices)

[88 92 74 95 61]
[29.99 14.5  99.    4.75]


In [12]:
# null matrix = [0,0,0,0]
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [ ]:
# unit matrix = [1,1,1,1]
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [15]:
print(np.arange(0, 10, 2))  # start, stop,step

[0 2 4 6 8]


In [20]:
print(np.linspace(0, 1, 5))  # 5 evenly spaced values from 0 to 1

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
print(np.random.randint(1, 7, 1))   # 5 random integers between 1 and 99

[6]


In [31]:
data = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print(data.shape)    # (rows, columns) (3,4)
print(data.dtype)    # data type of elements
print(data.ndim)     # number of dimensions
print(data.size)     # total number of elements

(3, 4)
int64
2
12


In [34]:
a = np.array([1, 2, 3])
b = np.array([1.0, 2.0, 3.0])
c = np.array([1, 2, 3], dtype=np.float32)

print(a.dtype)
print(b.dtype)
print(c.dtype)
print(a)
print(c)


int64
float64
float32
[1 2 3]
[1. 2. 3.]


In [37]:
temps = np.array([22, 25, 19, 30, 28, 24, 21])
print(temps[2])
print(temps[-1])
print(temps[-3])

19
21
28


In [38]:
print(temps[:3]) #

[22 25 19]


In [39]:
print(temps[2:6]) #

[19 30 28 24]


In [ ]:
temps = np.array([22, 25, 19, 30, 28, 24, 21])

print(temps[6:4:-1]) #
print(temps[-1:-3:-1]) # right to left 

[21 24]
[21 24]


In [ ]:
print(temps[-3:]) # left to right


[28 24 21]


In [66]:
grid = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])

print(grid[0, 0])      # row 0, col 0  → 1
print(grid[1, 1])   
print(grid[1, 3])   
print(grid[2, 2])   

1
6
8
11


In [ ]:
print(grid[1, 0:2])   

[5 6]


In [70]:
grid = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])

print(grid[1, 1:3])   

[6 7]


In [71]:
print(grid[2, 1:3])   

[10 11]


In [72]:
# [[5,6]
#  [9, 10]]
print(grid[1:3 , 0:2])   

[[ 5  6]
 [ 9 10]]
